# Camera configuration
cameraName = "Camera1"

# FTP server configuration
ftpServerAddress = "INSERT FTP SERVER ADDRESS HERE"
username = "INSERT FTP USERNAME HERE"
password = "INSERT FTP PASSWORD HERE"
ftpDirectory = ""
multipleCamerasOnServer = False

# Disable internet
localOnly = False