# Camera configuration
lensPosition = 0.0 # min = 0.0, max = 32.0, default = 1.0, autofocus = -1.0
resolution = (3280, 2464)

# Timer configuration
startTimeHour = 8
startTimeMinute = 0
intervalMinutes = 60
maxDurationMinute = 5
repetitionsPerday = 8

# GPS configuration
enableGPS = False # Log GPS coordinates

# Development configuration
shutdown = True # Enable/disable shutdown of pi after program has run