cameraName: "Camera1"

# Camera settings
# -1.0 is Autofocus
# 0.0 is infinity TODO
lensPosition: -1.0

# Select camera resolution
# Select [0, 0] for maximum resolution
# Has to be between 64x64 and 4608x2592
resolution: [0, 0]

# Change camera timer schedule in UTC
startTimeHour: 8
startTimeMinute: 0
intervalMinutes: 30
repetitionsPerday: 16
timeSync: false # Enable or disable time synchronization with internet

# Sunrise and sunset calculation for schedule (overrides schedule, needs location)
enableSunriseSunset: false

# Location settings
enableGPS: false # Enable or disable GPS module
location_overwrite: false # Manually override location (set location below)
latitude: 0.0
longitude: 0.0
height: 0

# Diagnostics data
logLevel: "INFO"
uploadWittyPiDiagnostics: false

# Voltage thresholds
low_voltage_threshold: 0.0 # Camera will shutdown if voltage drops below this value
recovery_voltage_threshold: 0.0 # Camera will restart if voltage rises above this value
battery_voltage_half: 12.0 # Battery voltage at 50% capacity

shutdown: false # Enable or disable shutdown after program has run

# When adding new settings, make sure to also add them to the settings class for proper settings validation